// lib/product.ts

export type CategorySlug = "xira-domisi" | "ydravlika" | "monotika";

export const CATEGORIES: Record<CategorySlug, string> = {
  "xira-domisi": "Ξηρά Δόμηση",
  "ydravlika": "Υδραυλικά",
  "monotika": "Μονωτικά",
};

export type Product = {
  id: string;
  slug: string;
  name: string;
  image: string;   // π.χ. "/images/products/ydravlika/valvida-antepistrofis.jpg"
  price?: number;
  unit?: string;
  category: CategorySlug;
  keywords?: string[];
  description?: string;
};

export const PRODUCTS: Product[] = [
  // ========= ΞΗΡΑ ΔΟΜΗΣΗ =========
  {
  id: "x5",
  slug: "kanali-orofis",
  name: "Κανάλι οροφής",
  image: "/images/products/xira-domisi/kanali.jpg",
  category: "xira-domisi",
  unit: "τμχ",
  keywords: ["κανάλι", "οροφής", "profil", "u"],
  description: "Κανάλι οροφής για σκελετούς ξηράς δόμησης.",
},
{
  id: "x6",
  slug: "perimetriko",
  name: "Περιμετρικό",
  image: "/images/products/xira-domisi/perimetriko.jpg",
  category: "xira-domisi",
  unit: "τμχ",
  keywords: ["στρωτήρας", "περιμετρικό", "profil", "u"],
  description: "Στρωτήρας περιμετρικός για σκελετούς γυψοσανίδας.",
},
{
  id: "x7",
  slug: "orthostatis",
  name: "Ορθοστάτης",
  image: "/images/products/xira-domisi/orthostatis.jpg",
  category: "xira-domisi",
  unit: "τμχ",
  keywords: ["ορθοστάτης", "profil", "c"],
  description: "Ορθοστάτης μεταλλικός για κατακόρυφους σκελετούς.",
},
{
  id: "x8",
  slug: "strotiras",
  name: "Στρωτήρας",
  image: "/images/products/xira-domisi/strotiras.jpg",
  category: "xira-domisi",
  unit: "τμχ",
  keywords: ["στρωτήρας", "profil", "u"],
  description: "Στρωτήρας για σκελετούς ξηράς δόμησης.",
},
{
  id: "x9",
  slug: "gypsosanida-apli",
  name: "Γυψοσανίδα απλή",
  image: "/images/products/xira-domisi/apli.jpg",
  category: "xira-domisi",
  unit: "τμχ",
  keywords: ["gypsosanida", "απλή", "ξηρά δόμηση"],
  description: "Τυπική γυψοσανίδα για εσωτερικές εφαρμογές.",
},
{
  id: "x10",
  slug: "gypsosanida-anthygri",
  name: "Γυψοσανίδα ανθυγρή",
  image: "/images/products/xira-domisi/anthigri.jpg",
  category: "xira-domisi",
  unit: "τμχ",
  keywords: ["gypsosanida", "ανθυγρή", "υγροί χώροι"],
  description: "Ανθυγρή γυψοσανίδα για μπάνια και κουζίνες.",
},
{
  id: "x11",
  slug: "gypsosanida-pirantoxi",
  name: "Γυψοσανίδα πυράντοχη",
  image: "/images/products/xira-domisi/pirantoxi.jpg",
  category: "xira-domisi",
  unit: "τμχ",
  keywords: ["gypsosanida", "πυράντοχη", "fire"],
  description: "Πυράντοχη γυψοσανίδα για αυξημένες απαιτήσεις πυροπροστασίας.",
},
{
  id: "x12",
  slug: "inosanida",
  name: "Ινοσανίδα",
  image: "/images/products/xira-domisi/inosanida.jpg",
  category: "xira-domisi",
  unit: "τμχ",
  keywords: ["inosanida", "ινοσανίδα", "πλάκα"],
  description: "Ινογυψοσανίδα υψηλής αντοχής.",
},
{
  id: "x13",
  slug: "tsimentosanida",
  name: "Τσιμεντοσανίδα",
  image: "/images/products/xira-domisi/tsimentosanida.jpg",
  category: "xira-domisi",
  unit: "τμχ",
  keywords: ["tsimentosanida", "τσιμεντοσανίδα", "εξωτερικού χώρου"],
  description: "Τσιμεντοσανίδα για υγρούς και εξωτερικούς χώρους.",
},
{
  id: "x14",
  slug: "agkistro",
  name: "Άγκιστρο",
  image: "/images/products/xira-domisi/agkistro.jpg",
  category: "xira-domisi",
  unit: "τμχ",
  keywords: ["άγκιστρο", "suspension", "profil"],
  description: "Άγκιστρο ανάρτησης για προφίλ οροφής.",
},
{
  id: "x15",
  slug: "sindetiras-p",
  name: "Συνδετήρας Π",
  image: "/images/products/xira-domisi/sindetiras-P.jpg",
  category: "xira-domisi",
  unit: "τμχ",
  keywords: ["συνδετήρας", "P", "connector", "profil"],
  description: "Συνδετήρας τύπου Π για προφίλ.",
},
{
  id: "x16",
  slug: "sindetiras-m",
  name: "Συνδετήρας M",
  image: "/images/products/xira-domisi/sindetiras-M.jpg",
  category: "xira-domisi",
  unit: "τμχ",
  keywords: ["συνδετήρας", "M", "connector", "profil"],
  description: "Συνδετήρας τύπου M για προφίλ.",
},
{
  id: "x17",
  slug: "anartisi",
  name: "Ανάρτηση",
  image: "/images/products/xira-domisi/anartisi.jpg",
  category: "xira-domisi",
  unit: "τμχ",
  keywords: ["ανάρτηση", "suspension", "profil", "οροφή"],
  description: "Ανάρτηση για σκελετούς οροφής ξηράς δόμησης.",
},
{
  id: "x19",
  slug: "karfoto-visma",
  name: "Καρφωτό βύσμα",
  image: "/images/products/xira-domisi/visma.jpg",
  category: "xira-domisi",
  unit: "τμχ",
  keywords: ["βύσμα", "καρφωτό", "visma", "γυψοσανίδα"],
  description: "Καρφωτό βύσμα για στερεώσεις σε γυψοσανίδα.",
},
{
  id: "x20",
  slug: "metalliko-visma",
  name: "Μεταλλικό βύσμα",
  image: "/images/products/xira-domisi/metvisma.jpg",
  category: "xira-domisi",
  unit: "τμχ",
  keywords: ["βύσμα", "μεταλλικό", "visma", "γυψοσανίδα", "θυρίδα"],
  description: "Μεταλλικό βύσμα – κατάλληλο και για θυρίδα γυψοσανίδας.",
},
{
  id: "x21",
  slug: "goniokrano",
  name: "Γωνιόκρανο",
  image: "/images/products/xira-domisi/goniokrana.jpg",
  category: "xira-domisi",
  unit: "τμχ",
  keywords: ["γωνιόκρανο", "corner bead", "profil", "ενισχυτικό", "άκρες"],
  description: "Γωνιόκρανο για ενίσχυση ακμών σε τοίχους/οροφές.",
},
{
  id: "x22",
  slug: "kaminades-anoksidotes",
  name: "Καμινάδες ανοξείδωτες",
  image: "/images/products/xira-domisi/kaminada.jpg",
  category: "xira-domisi",
  unit: "τμχ",
  keywords: ["καμινάδα", "ανοξείδωτη", "inox", "καπναγωγός"],
  description: "Ανοξείδωτες καμινάδες/σωλήνες καπναγωγού.Διαστάσεις :Φ80-300",
},
{
  id: "x23",
  slug: "kapelo-kaminadas",
  name: "Καπέλο καμινάδας",
  image: "/images/products/xira-domisi/kapelo.jpg",
  category: "xira-domisi",
  unit: "τμχ",
  keywords: ["καπέλο", "καμινάδας", "καπναγωγός", "κάλυμμα"],
  description: "Καπέλο καμινάδας για προστασία από βροχή/ανεμοπίεση.Διαστάσεις :Φ80-300",
},
{
  id: "x24",
  slug: "spiral-alouminio",
  name: "Σπιράλ αλουμινίου",
  image: "/images/products/xira-domisi/spiral-aloum.jpg",
  category: "xira-domisi",
  unit: "μ.",
  keywords: ["σπιράλ", "αλουμινίου", "εύκαμπτος αγωγός", "εξαερισμός"],
  description: "Εύκαμπτος αγωγός αλουμινίου για εξαερισμό/καπναγωγούς.Διαστάσεις :Φ80-300",
},
{
  id: "x25",
  slug: "tainia-armou",
  name: "Ταινία αρμού",
  image: "/images/products/xira-domisi/tainia-armou.jpg",
  category: "xira-domisi",
  unit: "τμχ",
  keywords: ["ταινία", "αρμού", "joint tape", "γυψοσανίδα"],
  description: "Ταινία αρμού για ενίσχυση ενώσεων γυψοσανίδας.",
},
{
  id: "x26",
  slug: "iliko-armou",
  name: "Υλικό αρμού",
  image: "/images/products/xira-domisi/iliko-armou.jpg",
  category: "xira-domisi",
  unit: "δοχ.",
  keywords: ["υλικό", "αρμού", "joint compound", "στόκος", "γυψοσανίδα"],
  description: "Υλικό αρμού (στόκος) για στοκάρισμα ενώσεων γυψοσανίδας.",
},





  // ========= ΥΔΡΑΥΛΙΚΑ =========
  {
    id: "u1",
    slug: "tampoureto-episkepsis",
    name: "Ταμπουρέτο επίσκεψης",
    image: "/images/products/ydravlika/tampoureto-episkepsis.jpg",
    category: "ydravlika",
    unit: "τμχ",
    keywords: ["tampoureto", "επίσκεψης", "επισκέψεως", "καθαρισμού"],
    description: "Διαστάσεις: Φ250 (125–160), Φ315 (125–160).",
  },
  {
    id: "u2",
    slug: "valvida-antepistrofis",
    name: "Βαλβίδα αντεπιστροφής",
    image: "/images/products/ydravlika/valvida-antepistrofis.jpg",
    category: "ydravlika",
    unit: "τμχ",
    keywords: ["αντεπίστροφο", "βαλβίδα", "check valve"],
    description: "Διαθέσιμες διαμέτρους: Φ100, Φ110, Φ125, Φ160.",
  },
  {
    id: "u3",
    slug: "tampoureto-vareos-typou",
    name: "Ταμπουρέτο βαρέως τύπου",
    image: "/images/products/ydravlika/tampoureto-vareos-typou.jpg",
    category: "ydravlika",
    unit: "τμχ",
    keywords: ["tampoureto", "βαρέως", "heavy duty"],
    description: "Διαστάσεις: Φ315 (125–160–200).",
  },
  {
    id: "u4",
    slug: "tapes-episkepsis",
    name: "Τάπες επίσκεψης",
    image: "/images/products/ydravlika/tapes-episkepsis.jpg",
    category: "ydravlika",
    unit: "τμχ",
    keywords: ["τάπα", "επισκέψεως", "pvc cap"],
    description: "Διαστάσεις: Φ250–315.",
  },
  {
  id: "u14",
  slug: "sxara-sxismis-tipou-sxismis",
  name: "Σχάρα σχισμής όψης τύπου σχισμής",
  image: "/images/products/ydravlika/sxara-sxismis-tipou-sxismis.jpg",
  category: "ydravlika",
  unit: "τμχ",
  keywords: ["σχάρα", "σχισμής", "αόρατη", "πεζών", "ελαφρά οχήματα"],
  description: "Αόρατη σχάρα για πεζούς/ελαφρά οχήματα.",
},
{
  id: "u15",
  slug: "kanali-xamilou-ipsous",
  name: "Κανάλι χαμηλού ύψους 1m × 130mm (σκούρο γκρι)",
  image: "/images/products/ydravlika/kanali-xamilou-ipsous.jpg",
  category: "ydravlika",
  unit: "τμχ",
  keywords: ["κανάλι", "χαμηλού ύψους", "1m", "130mm"],
},
{
  id: "u16",
  slug: "nahj13-kalyma-prosorino",
  name: "Προσωρινό κάλυμμα NAHJ13 (Connecto)",
  image: "/images/products/ydravlika/nahj13.jpg",
  category: "ydravlika",
  unit: "τμχ",
  keywords: ["προσωρινό", "κάλυμμα", "connecto", "NAHJ13"],
  description: "Προσωρινό κάλυμμα καναλιού για διαχείριση στεγανοποίησης.",
},
{
  id: "u17",
  slug: "nahj13-termatiki-exodos-40-50",
  name: "Τερματική έξοδος Φ40/50 (γκρι)",
  image: "/images/products/ydravlika/nahj13termatiki.jpg",
  category: "ydravlika",
  unit: "τμχ",
  keywords: ["τερματική", "έξοδος", "Φ40", "Φ50", "connecto"],
  description: "Προσαρμογή/τερματισμός για κανάλι απορροής.",
},
{
  id: "u18",
  slug: "jcab13-enosi-kanaliou",
  name: "Ένωση για κανάλι",
  image: "/images/products/ydravlika/jcab13.jpg",
  category: "ydravlika",
  unit: "τμχ",
  keywords: ["ένωση", "connector", "κανάλι"],
  description: "Σύνδεσμος για ένωση τμημάτων καναλιού.",
},
{
  id: "u19",
  slug: "kanali-poliamidiou-b125-connecto",
  name: "Κανάλι με σχάρα πολυαμιδίου B125 (L100/130) Connecto",
  image: "/images/products/ydravlika/can10bn125.jpg",
  category: "ydravlika",
  unit: "τμχ",
  keywords: ["κανάλι", "πολυαμίδιο", "B125", "Connecto", "σχάρα"],
},
{
  id: "u20",
  slug: "kanali-0-5m-130mm-gri-773",
  name: "Κανάλι χαμηλό 0,5m × 130mm (γκρι) 773",
  image: "/images/products/ydravlika/cab773.jpg",
  category: "ydravlika",
  unit: "τμχ",
  keywords: ["κανάλι", "0.5m", "130mm", "γκρι", "773"],
},
{
  id: "u21",
  slug: "sxara-inox-a15-1m",
  name: "Σχάρα ΙΝΟΧ κλάσης A15 (1m)",
  image: "/images/products/ydravlika/gdr10api.jpg",
  category: "ydravlika",
  unit: "τμχ",
  keywords: ["σχάρα", "INOX", "A15", "1m"],
},


  {
  id: "u22",
  slug: "freatio-pp",
  name: "Φρεάτιο PP",
  image: "/images/products/ydravlika/freatiopp.jpg",
  category: "ydravlika",
  unit: "τμχ",
  keywords: ["φρεάτιο", "PP", "υδραυλικά"],
},
{
  id: "u23",
  slug: "kapaki-pvc-elafria-oximata",
  name: "Καπάκι PVC για ελαφριά διέλευση οχημάτων",
  image: "/images/products/ydravlika/kapakifraetio.jpg", // προσοχή: φάκελος ydravlika
  category: "ydravlika",
  unit: "τμχ",
  keywords: ["καπάκι", "PVC", "ελαφριά οχήματα"],
},
{
  id: "u24",
  slug: "kapaki-freatiou-pp-epifaneia",
  name: "Καπάκι φρεατίου PP (τελική επιφάνεια)",
  image: "/images/products/ydravlika/kapakifrpp.jpg",
  category: "ydravlika",
  unit: "τμχ",
  keywords: ["καπάκι", "φρεατίου", "PP"],
  description: "Με δυνατότητα τελικής επιφάνειας.",
},
{
  id: "u25",
  slug: "kapaki-freatiou-pvc-epifaneia-cheroulo",
  name: "Καπάκι φρεατίου PVC (τελική επιφάνεια, χερούλι)",
  image: "/images/products/ydravlika/kapakipvc.jpg",
  category: "ydravlika",
  unit: "τμχ",
  keywords: ["καπάκι", "φρεατίου", "PVC", "χερούλι"],
},
{
  id: "u26",
  slug: "sxara-pvc-elafria-oximata",
  name: "Σχάρα PVC για ελαφριά διέλευση οχημάτων",
  image: "/images/products/ydravlika/sxarapvc.jpg",
  category: "ydravlika",
  unit: "τμχ",
  keywords: ["σχάρα", "PVC", "οχήματα"],
},
{
  id: "u27",
  slug: "freatio-orizontia-100x90",
  name: "Φρεάτιο οριζόντια 100×90",
  image: "/images/products/ydravlika/freatio-orizontia.jpg",
  category: "ydravlika",
  unit: "τμχ",
  keywords: ["φρεάτιο", "οριζόντια", "100x90"],
},
{
  id: "u28",
  slug: "sifoni-dapedou-wc-3-eisodoi",
  name: "Σιφώνι δαπέδου WC με 3 εισόδους",
  image: "/images/products/ydravlika/sif-dap.jpg",
  category: "ydravlika",
  unit: "τμχ",
  keywords: ["σιφώνι", "δαπέδου", "WC", "3 εισόδοι"],
  description: "Διαστάσεις καπακιού: 15×15, 20×20.",
},
{
  id: "u29",
  slug: "sifoni-mpalkoni-orizontia-exodos-f32",
  name: "Σιφώνι μπαλκονιού/ντουζιέρας οριζόντιας εξόδου Φ32",
  image: "/images/products/ydravlika/sif-mpalkoni.jpg",
  category: "ydravlika",
  unit: "τμχ",
  keywords: ["σιφώνι", "μπαλκονιού", "ντουζιέρας", "οριζόντια έξοδος", "Φ32"],
},
{
  id: "u30",
  slug: "katakorifi-exodos-anoks-sxaraki",
  name: "Κατακόρυφη έξοδος με ανοξείδωτο σχαράκι",
  image: "/images/products/ydravlika/katak-eksodos-anoks-sxaraki.jpg",
  category: "ydravlika",
  unit: "τμχ",
  keywords: ["έξοδος", "κατακόρυφη", "INOX", "σχαράκι"],
},
{
  id: "u31",
  slug: "kapaki-pvc-pezous-cherouli",
  name: "Καπάκι PVC για πεζούς με χερούλι",
  image: "/images/products/ydravlika/kapakixerouli.jpg",
  category: "ydravlika",
  unit: "τμχ",
  keywords: ["καπάκι", "PVC", "πεζούς", "χερούλι"],
},
{
  id: "u32",
  slug: "plaisio-pvc",
  name: "Πλαίσιο PVC",
  image: "/images/products/ydravlika/plaisiopvc.jpg",
  category: "ydravlika",
  unit: "τμχ",
  keywords: ["πλαίσιο", "PVC", "καπάκι", "φρεάτιο"],
},
{
  id: "u33",
  slug: "freatio-pp-alt",
  name: "Φρεάτιο PP",
  image: "/images/products/ydravlika/freapppp.jpg",
  category: "ydravlika",
  unit: "τμχ",
  keywords: ["φρεάτιο", "PP", "υδραυλικά"],
},

  {
    id: "u5",
    slug: "anapodi-sistoli",
    name: "Ανάποδη συστολή",
    image: "/images/products/ydravlika/anapodi-sistoli.jpg",
    category: "ydravlika",
    unit: "τμχ",
    keywords: ["συστολή", "αναποδη", "μείωση"],
    description: "Διαστάσεις: Φ110–125–160–200.",
  },
  {
    id: "u6",
    slug: "gwnia-15",
    name: "Γωνία 15°",
    image: "/images/products/ydravlika/gwnia-15.jpg",
    category: "ydravlika",
    unit: "τμχ",
    keywords: ["γωνία", "15", "μοίρες", "λυμάτων"],
    description: "Διαστάσεις: Φ110–125–160–200.",
  },
  {
    id: "u7",
    slug: "gwnia-30",
    name: "Γωνία 30°",
    image: "/images/products/ydravlika/gwnia-30.jpg",
    category: "ydravlika",
    unit: "τμχ",
    keywords: ["γωνία", "30", "μοίρες", "λυμάτων"],
    description: "Διαστάσεις: Φ110–125–160–200.",
  },
  {
    id: "u8",
    slug: "gwnia-45",
    name: "Γωνία 45°",
    image: "/images/products/ydravlika/gwnia-45.jpg",
    category: "ydravlika",
    unit: "τμχ",
    keywords: ["γωνία", "45", "μοίρες", "λυμάτων"],
    description: "Διαστάσεις: Φ110–125–160–200.",
  },
  {
  id: "u9",
  slug: "imitaf-45",
  name: "Ημιτάφ 45°",
  image: "/images/products/ydravlika/imitaf-45.jpg",
  category: "ydravlika",
  unit: "τμχ",
  keywords: ["ημιτάφ", "Y", "45", "μοίρες", "λυμάτων"],
  description: "Διαστάσεις: Φ110–125–160–200.",
},
{
  id: "u10",
  slug: "imitaf-systoliko-45",
  name: "Ημιτάφ συστολικό 45°",
  image: "/images/products/ydravlika/imitaf-systoliko-45.jpg",
  category: "ydravlika",
  unit: "τμχ",
  keywords: ["ημιτάφ", "συστολικό", "Y", "45", "μείωση"],
  description: "Διαστάσεις: Φ110–125–160–200.",
},
{
  id: "u11",
  slug: "antaptoras",
  name: "Αντάπτορας",
  image: "/images/products/ydravlika/antaptoras.jpg",
  category: "ydravlika",
  unit: "τμχ",
  keywords: ["adapter", "αντάπτορας"],
  description: "Διαστάσεις: Φ110–125–160–200.",
},
{
  id: "u12",
  slug: "imitaf-diplo-parallilo-45",
  name: "Ημιτάφ διπλό παράλληλο 45°",
  image: "/images/products/ydravlika/imitaf-diplo-parallilo-45.jpg",
  category: "ydravlika",
  unit: "τμχ",
  keywords: ["ημιτάφ", "διπλό", "παράλληλο", "Y", "45", "μοίρες"],
  description: "Διαστάσεις: Φ110–125–160–200.",
},
{
  id: "u13",
  slug: "lmlm1515-grey",
  name: "LMLM1515 Grey",
  image: "/images/products/ydravlika/lmlm1515-grey.jpg",
  category: "ydravlika",
  unit: "τμχ",
  keywords: ["lmlm1515", "grey", "γκρι", "χρώμα"],
  description: "Χρώμα: γκρι.",
},
{
  id: "x18",
  slug: "vida-gypsosanidas-metaliki",
  name: "Βίδα Γυψοσανίδας Μεταλλική",
  image: "/images/products/xira-domisi/vida.jpg",
  category: "xira-domisi",
  unit: "κιβ.",
  keywords: ["βίδα", "γυψοσανίδας", "μεταλλική", "M3.5", "25mm", "35mm"],
  description: "Διάμετρος M3.5  μήκος: 25mm, 35mm.",
},




  // ========= ΜΟΝΩΤΙΚΑ =========
{
  id: "m1",
  slug: "petrovamvakas-rolo",
  name: "Πετροβάμβακας ρολό",
  image: "/images/products/monotika/petrovamvakas-rolo.jpg",
  category: "monotika",
  unit: "m²",
  keywords: ["πετροβάμβακας", "ρολό", "petrovamvakas", "μονωτικό"],
  description: "Ρολά πετροβάμβακα για θερμοηχομόνωση τοιχοποιίας & οροφών.",
},
{
  id: "m2",
  slug: "petrovamvakas-fillo",
  name: "Πετροβάμβακας φύλλο",
  image: "/images/products/monotika/petrovamvakas-fillo.jpg",
  category: "monotika",
  unit: "m²",
  keywords: ["πετροβάμβακας", "φύλλο", "petrovamvakas", "μονωτικό"],
  description: "Φύλλα πετροβάμβακα για θερμοηχομόνωση τοιχοποιίας & δαπέδων.",
},
{
  id: "m3",
  slug: "nano-proof-ceramic-ds-270",
  name: "Nano Proof Ceramic DS-270",
  image: "/images/products/monotika/nano-ceramic.jpg",
  category: "monotika",
  keywords: ["nano proof", "ceramic", "ds-270", "υδαταπωθητικό", "σοβά", "μπετόν", "πέτρα", "πήλινα"],
  description: "Yδαταπωθητικό για σοβά, μπετόν, πήλινες & πέτρινες επιφάνειες.",
},
{
  id: "m4",
  slug: "afrostokos",
  name: "Αφρόστοκος",
  image: "/images/products/monotika/afrostokos.jpg",
  category: "monotika",
  keywords: ["αφρόστοκος", "ελαφροβαρής", "ακρυλικός", "στόκος"],
  description: "Ελαφροβαρής επισκευαστικός ακρυλικός στόκος.",
},
{
  id: "m5",
  slug: "d-32",
  name: "D-32",
  image: "/images/products/monotika/D-32.jpg",
  category: "monotika",
  keywords: ["d-32", "ταχύπηκτος", "σοβάς", "λευκός"],
  description: "Ταχύπηκτος επισκευαστικός λευκός σοβάς.",
},
{
  id: "m6",
  slug: "durowood",
  name: "Durowood",
  image: "/images/products/monotika/durowood.jpg",
  category: "monotika",
  keywords: ["durowood", "ξυλόστοκος", "ακρυλικός", "νερού"],
  description: "Ακρυλικός ξυλόστοκος νερού.",
},
{
  id: "m7",
  slug: "52-5-plus",
  name: "52,5 Plus",
  image: "/images/products/monotika/plus52.jpg",
  category: "monotika",
  keywords: ["52,5", "52.5", "plus", "υδραυλικό συνδετικό", "τσιμέντο"],
  description: "Yδραυλικό συνδετικό με βάση το τσιμέντο.",
},
{
  id: "m8",
  slug: "super-flex-powder",
  name: "Super Flex Powder",
  image: "/images/products/monotika/Super-flex-powder.jpg",
  category: "monotika",
  keywords: ["super", "flex", "powder", "ινοπλισμένο", "τσιμεντοειδές", "σφραγιστικό", "ρωγμές"],
  description: "Εύκαμπτο, ινοπλισμένο τσιμεντοειδές σφραγιστικό για ρωγμές 1–15mm.",
},
{
  id: "m9",
  slug: "power-thermo",
  name: "Power Thermo",
  image: "/images/products/monotika/power-thermo.jpg",
  category: "monotika",
  keywords: ["power thermo", "κόλλα αφρού", "πολυουρεθάνης", "θερμομόνωση"],
  description: "Κόλλα αφρού πολυουρεθάνης χαμηλής διόγκωσης για θερμομονωτικές πλάκες.",
},
{
  id: "m10",
  slug: "d-2",
  name: "D-2",
  image: "/images/products/monotika/D-2.jpg",
  category: "monotika",
  keywords: ["d-2", "αφρός", "πολυουρεθάνης", "ενός συστατικού"],
  description: "Αφρός πολυουρεθάνης ενός συστατικού.",
},
{
  id: "m11",
  slug: "no39",
  name: "Νο39",
  image: "/images/products/monotika/No39.jpg",
  category: "monotika",
  keywords: ["No39", "ελαστομερές", "στεγανωτικό", "ταρατσών"],
  description: "Ελαστομερές στεγανωτικό ταρατσών.",
},
{
  id: "m12",
  slug: "ds-255",
  name: "DS-255",
  image: "/images/products/monotika/DS-255.jpg",
  category: "monotika",
  keywords: ["DS-255", "αστάρι", "ακρυλικό", "πρόσφυση", "κονιάματα"],
  description: "Χαλαζιακό ακρυλικό αστάρι πρόσφυσης κονιαμάτων, χωρίς διαλύτες.",
},
{
  id: "m13",
  slug: "hobby",
  name: "Hobby",
  image: "/images/products/monotika/hobby.jpg",
  category: "monotika",
  keywords: ["κόλλα", "ξύλου", "χάρτου", "κρυσταλλιζέ"],
  description: "Κόλλα ξύλου & χάρτου κρυσταλλιζέ.",
},
{
  id: "m14",
  slug: "silicone",
  name: "Σιλικόνη",
  image: "/images/products/monotika/Silicone.jpg",
  category: "monotika",
  keywords: ["σιλικόνη", "μούχλα", "sanitary"],
  description: "Ανθεκτική στη μούχλα.",
},
{
  id: "m15",
  slug: "fireproof",
  name: "Fireproof",
  image: "/images/products/monotika/Fireproof.jpg",
  category: "monotika",
  keywords: ["πυράντοχο", "σφραγιστικό", "1200°C"],
  description: "Πυράντοχο σφραγιστικό έως +1.200°C.",
},
{
  id: "m16",
  slug: "akrylikos-stokos",
  name: "Ακρυλικός στόκος",
  image: "/images/products/monotika/akrylikos stokos.jpg",
  category: "monotika",
  keywords: ["ακρυλικός", "στόκος", "βαφόμενος", "σιλικονούχος"],
  description: "Σιλικονούχος βαφόμενος.",
},
{
  id: "m17",
  slug: "rust-free",
  name: "Rust Free",
  image: "/images/products/monotika/Rust_Free.jpg",
  category: "monotika",
  keywords: ["antiskoriako", "λιπαντικό", "rust free"],
  description: "Αντισκωριακό και λιπαντικό.",
},
{
  id: "m18",
  slug: "d-20",
  name: "D-20",
  image: "/images/products/monotika/D-20.jpg",
  category: "monotika",
  keywords: ["D-20", "πρόσμικτο", "ακρυλικό", "γαλάκτωμα"],
  description: "Πρόσμικτο ακρυλικό γαλάκτωμα κονιαμάτων.",
},
{
  id: "m19",
  slug: "d-1",
  name: "D-1",
  image: "/images/products/monotika/D-1.jpg",
  category: "monotika",
  keywords: ["D-1", "στεγανοποίηση", "κονίαμα"],
  description: "Επαλειφόμενο κονίαμα στεγανοποίησης τοιχίων, δαπέδων, υπογείων & στεγών.",
},
{
  id: "m20",
  slug: "tsimentoeidis-sovas",
  name: "Τσιμεντοειδής σοβάς",
  image: "/images/products/monotika/isomat.jpg",
  category: "monotika",
  keywords: ["τσιμεντοειδής", "σοβάς", "ρητινούχος", "υδαταπωθητικός", "έγχρωμος", "λεία επιφάνεια"],
  description: "Ρητινούχος, έγχρωμος, υδαταπωθητικός, τσιμεντοειδής σοβάς. Λεία επιφάνεια.",
},
{
  id: "m21",
  slug: "baumit-procontact-gel",
  name: "Baumit ProContact Gel Κόλλα Θερμοπρόσοψης",
  image: "/images/products/monotika/procontact.jpg",
  category: "monotika",
  keywords: ["Baumit", "ProContact", "Gel", "θερμοπρόσοψη", "επικόλληση", "στρώση ενίσχυσης"],
  description: "Ανόργανη κονία επικόλλησης και στρώσης ενίσχυσης.",
},
{
  id: "m22",
  slug: "gypsos-kallitehnias-knauf",
  name: "ΓΥΨΟΣ ΚΑΛΛΙΤΕΧΝΙΑΣ KNAUF",
  image: "/images/products/monotika/knauf-gipsos.jpg",
  category: "monotika",
  keywords: ["γύψος", "καλλιτεχνίας", "Knauf"],
},
{
  id: "m23",
  slug: "acrylic-kolla-plakidion",
  name: "Acrylic (Ακρυλική) Κόλλα πλακιδίων",
  image: "/images/products/monotika/acrylic.jpg",
  category: "monotika",
  keywords: ["acrylic", "ακρυλική", "κόλλα πλακιδίων", "λευκή", "ρητίνες"],
  description: "Τσιμεντοειδής, λευκή κόλλα πλακιδίων, ενισχυμένη με ρητίνες ακρυλικής βάσης.",
},
{
  id: "m24",
  slug: "ekselasmeni-polisterini",
  name: "Εξελασμένη πολυστερίνη",
  image: "/images/products/monotika/ekselasmeni-polisterini.jpg",
  category: "monotika",
  unit: "m²",
  keywords: ["XPS", "εξηλασμένη", "εξελασμένη", "πολυστερίνη", "μονωτικό"],
  description: "Πλάκες εξηλασμένης πολυστερίνης (XPS) για θερμομόνωση.",
},
{
  id: "m25",
  slug: "grafitouxo-felizol",
  name: "Γραφιτούχο φελιζόλ",
  image: "/images/products/monotika/grafitouxo-felizol.jpg",
  category: "monotika",
  unit: "m²",
  keywords: ["EPS", "γραφιτούχο", "φελιζόλ", "θερμομόνωση"],
  description: "Διογκωμένη πολυστερίνη (EPS) με γραφίτη για βελτιωμένες θερμομονωτικές ιδιότητες.",
},
{
  id: "m26",
  slug: "orixtovamvakas",
  name: "Ορυκτοβάμβακας",
  image: "/images/products/monotika/orixtovamvakas.jpg",
  category: "monotika",
  unit: "m²",
  keywords: ["ορυκτοβάμβακας", "μονωτικό", "ηχομονωτικό", "mineral wool"],
  description: "Μονωτικό/ηχομονωτικό. Διαστάσεις: 1.33×0.60 και 1.26×0.60 .",
},



];

export function findProductBySlug(slug: string): Product | undefined {
  return PRODUCTS.find((p) => p.slug === slug);
}
